version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    target-branch: "preview"
    open-pull-requests-limit: 5
    reviewers:
      - "iKarTehFox"
    assignees:
      - "iKarTehFox"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sass"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]